version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis-master:
    image: redis:5.0.5
    container_name: redis-master
    ports:
      - 6379:6379
    networks:
      - app-tier
#  redis-slave:
#    image: redis:5.0.5
#    container_name: redis-slave
#    command: redis-server --slaveof redis-master 6379
#    depends_on:
#      - redis-master
#    ports:
#      - 6379:6379
#    networks:
#      - app-tier

  sentinel:
    image: redis-sentinel
    build: .
    container_name: redis-sentinel
    environment:
      - MSTER=redis-master  #redis-master地址
      - MASTER_NAME=mymaster-1
      - QUORUM=2
      - SENTINEL_PORT=26379
      - AUTH_PASS=123456
      - REDIS_PORT=6379
    depends_on:
      - redis-master
#      - redis-slave
    ports:
      - 26379:26379
